import type { ReportForm, ReportFormId } from './reportTypes';
import {
	baseFields,
	field,
	lossOptionFields,
	lossOptionToggleFields,
	lossOptionsExpandedField,
	lossOptions,
	noValue,
	scopeOptionFields,
	scopeOptionToggleFields,
	scopeOptionsExpandedField,
	scopeOptions,
	threatCategoryField,
	threatCategoryGroups,
	threatOptions,
	yesValue,
} from './reportFields';

const detailReportsObject = 'XSC_SecurityReport__DetailReports';
const initialReportsObject = 'XSC_SecurityReport__InitialReports';

const initialWarning: ReportForm = {
	id: 'initialWarning',
	displayName: 'Initial Warning',
	objectName: initialReportsObject,
	fixedFields: {},
	fields: [
		baseFields.organization,
		baseFields.reporter,
		baseFields.reporterEmail,
		baseFields.reporterPhone,
		baseFields.reporterTitle,
		baseFields.externalTicketId,
		baseFields.summary,
		baseFields.detectedOn,
		baseFields.affectedEntities,
		baseFields.criminalOffence,
		baseFields.evidence,
		baseFields.intergovernmentalImpact,
		baseFields.intergovernmentalImpactValue,
		baseFields.helpNeeded,
		baseFields.helpDetails,
		baseFields.reported,
		baseFields.reportedValue,
		baseFields.otherInformation,
	],
	conditionalRequired: [
		{
			when: 'IntergovernmentalImpactYesNo',
			is: yesValue,
			require: ['IntergovernmentalImpactValue'],
		},
		{
			when: 'CyberIncidentResolvedHelpYesNo',
			is: yesValue,
			require: ['CyberIncidentResolvedHelpValue'],
		},
		{ when: 'CyberIncidentReportedYesNo', is: yesValue, require: ['CyberIncidentReportedValue'] },
	],
};

const majorIncident: ReportForm = {
	id: 'majorIncident',
	displayName: 'Major Cyber Incident',
	objectName: detailReportsObject,
	fixedFields: { TypeOfCyberIncident: 'Didelis' },
	fields: [
		baseFields.organization,
		baseFields.reporter,
		baseFields.reporterEmail,
		baseFields.reporterPhone,
		baseFields.reporterTitle,
		baseFields.externalTicketId,
		baseFields.summary,
		baseFields.detectedOn,
		scopeOptionsExpandedField,
		field({
			displayName: 'Scope Options',
			name: 'ScopeOptions',
			type: 'multiOptions',
			default: [],
			required: true,
			visibleWhen: { ScopeOptionsExpanded: [false] },
			description:
				'Select every condition that fits the incident. At least one selection is required.',
			options: scopeOptions,
			optionFields: scopeOptionFields,
		}),
		...scopeOptionToggleFields,
		field({
			displayName: 'Initial Report Update',
			name: 'InitialReportUpdateYesNo',
			type: 'yesNo',
			default: noValue,
			required: true,
			description: 'Whether the early-warning data will be updated',
		}),
		field({
			displayName: 'Reputation Impact',
			name: 'CyberIncidentReputationYesNo',
			type: 'yesNo',
			default: noValue,
			required: true,
			description: 'Whether the incident caused reputational impact',
		}),
		field({
			displayName: 'Reputation Impact Details',
			name: 'CyberIncidentReputationValue',
			type: 'string',
			default: '',
			rows: 3,
			description: 'Reputational impact',
		}),
		field({
			displayName: 'Resolved On',
			name: 'ResolvedOn',
			type: 'dateTime',
			default: '',
			description: 'Date and time the service disruption was resolved',
		}),
		baseFields.impactToPersons,
		lossOptionsExpandedField,
		field({
			displayName: 'Loss Options',
			name: 'LossOptions',
			type: 'multiOptions',
			default: [],
			visibleWhen: { LossOptionsExpanded: [false] },
			description: 'Select every loss condition that applies',
			options: lossOptions,
			optionFields: lossOptionFields,
		}),
		...lossOptionToggleFields,
		baseFields.affectedPersons,
		baseFields.resolved,
		baseFields.resolvedValue,
		baseFields.affectedServices,
		baseFields.financialLoss,
		baseFields.financialLossValue,
		baseFields.thirdPartyImpact,
		baseFields.thirdPartyValue,
		baseFields.evidence,
		field({
			...baseFields.recurrence,
			required: true,
		}),
		baseFields.otherInformation,
	],
	requiredOneOf: {
		fields: scopeOptionFields,
		message: 'At least one Scope Option must be selected',
	},
	conditionalRequired: [
		{
			when: 'CyberIncidentReputationYesNo',
			is: yesValue,
			require: ['CyberIncidentReputationValue'],
		},
		{
			when: 'ImpactToPersonYesNo',
			is: yesValue,
			require: ['AffectedPersons'],
			requireOneOf: lossOptionFields,
			message: 'At least one Loss Option must be selected when Impact To Persons is Yes',
		},
		{ when: 'CyberIncidentResolvedYesNo', is: noValue, require: ['CyberIncidentResolvedValue'] },
		{ when: 'FinancialLossYesNo', is: yesValue, require: ['FinancialLossValue'] },
		{ when: 'ImpactFromThirdPartyYesNo', is: yesValue, require: ['ImpactFromThirdPartyValue'] },
	],
};

const minorIncident: ReportForm = {
	id: 'minorIncident',
	displayName: 'Minor Cyber Incident',
	objectName: detailReportsObject,
	fixedFields: { TypeOfCyberIncident: 'Nedidelis' },
	fields: [
		baseFields.organization,
		baseFields.reporter,
		baseFields.reporterEmail,
		baseFields.reporterPhone,
		baseFields.reporterTitle,
		baseFields.externalTicketId,
		baseFields.summary,
		baseFields.detectedOn,
		baseFields.affectedEntities,
		baseFields.impactToPersons,
		baseFields.affectedPersons,
		baseFields.resolved,
		baseFields.resolvedValue,
		baseFields.criminalOffence,
		baseFields.affectedServices,
		baseFields.financialLoss,
		baseFields.financialLossValue,
		baseFields.thirdPartyImpact,
		baseFields.thirdPartyValue,
		baseFields.evidence,
		baseFields.helpNeeded,
		baseFields.helpDetails,
		baseFields.recurrence,
		field({ ...baseFields.reported, required: true }),
		baseFields.reportedValue,
		field({
			displayName: 'Final Report Update',
			name: 'FinalReportUpdateYesNo',
			type: 'yesNo',
			default: noValue,
			required: true,
			description: 'Whether a final incident report will be submitted',
		}),
		field({
			displayName: 'Threat',
			name: 'Threat',
			type: 'options',
			default: '',
			maxLength: 1000,
			description: 'Cyber threat',
			options: threatOptions,
		}),
		threatCategoryField,
		field({
			displayName: 'Cyber Incident Impact',
			name: 'CyberIncidentImpact',
			type: 'string',
			default: '',
			maxLength: 1000,
			rows: 3,
			description: 'Detailed description of the incident, including its severity and impact',
		}),
		field({
			displayName: 'Cyber Incident Mitigation',
			name: 'CyberIncidentMitigation',
			type: 'string',
			default: '',
			rows: 3,
			description: "Measures applied and implemented to mitigate the incident's impact",
		}),
		baseFields.intergovernmentalImpact,
		baseFields.intergovernmentalImpactValue,
		baseFields.otherInformation,
	],
	conditionalRequired: [
		{ when: 'ImpactToPersonYesNo', is: yesValue, require: ['AffectedPersons'] },
		{ when: 'CyberIncidentResolvedYesNo', is: noValue, require: ['CyberIncidentResolvedValue'] },
		{ when: 'FinancialLossYesNo', is: yesValue, require: ['FinancialLossValue'] },
		{ when: 'ImpactFromThirdPartyYesNo', is: yesValue, require: ['ImpactFromThirdPartyValue'] },
		{
			when: 'CyberIncidentResolvedHelpYesNo',
			is: yesValue,
			require: ['CyberIncidentResolvedHelpValue'],
		},
		{ when: 'CyberIncidentReportedYesNo', is: yesValue, require: ['CyberIncidentReportedValue'] },
		{
			when: 'FinalReportUpdateYesNo',
			is: noValue,
			require: ['Threat', 'CyberIncidentImpact', 'CyberIncidentMitigation'],
		},
		...threatCategoryGroups.map((group) => ({
			when: 'Threat',
			is: group.threat,
			require: ['ThreatCategory'],
		})),
		{
			when: 'IntergovernmentalImpactYesNo',
			is: yesValue,
			require: ['IntergovernmentalImpactValue'],
		},
	],
};

const nearMissIncident: ReportForm = {
	id: 'nearMissIncident',
	displayName: 'Near Miss Cyber Incident',
	objectName: detailReportsObject,
	fixedFields: { TypeOfCyberIncident: 'Vos neįvykęs' },
	fields: [
		baseFields.organization,
		baseFields.reporter,
		baseFields.reporterEmail,
		baseFields.reporterPhone,
		baseFields.reporterTitle,
		baseFields.externalTicketId,
		baseFields.summary,
		baseFields.detectedOn,
		baseFields.affectedEntities,
		field({
			displayName: 'Report',
			name: 'DetailReportDescription',
			type: 'string',
			default: '',
			required: true,
			rows: 3,
			description: 'Incident report description',
		}),
		baseFields.otherInformation,
	],
};

export const reportForms: Record<ReportFormId, ReportForm> = {
	initialWarning,
	majorIncident,
	minorIncident,
	nearMissIncident,
};
